services:
  app:
    build:
      context: .
      dockerfile: ../thingol/app/Dockerfile
    container_name: thingol
    links:
      - db
    ports:
      - "9000:5000"
    volumes:
      - ./:/thingol

  db:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
    