services:
  app:
    build:
      context: .
      dockerfile: ../thingol/app/Dockerfile
    container_name: thingol
    command: python3 -m flask run --host=0.0.0.0 --debug --reload
    links:
      - db
    ports:
      - "9000:5000"
    volumes:
      - ./app/src:/app

  db:
    image: mariadb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
    